In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
import pandas as pd
import tensorflow as tf

import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

ModuleNotFoundError: No module named 'tensorflow'

In [18]:
application_df = application_df.drop(["EIN","NAME"],1)

In [19]:
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [20]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df.APPLICATION_TYPE.value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [21]:
replace_application = list(application_counts[application_counts < 500].index)

# Replace in dataframe
for app in replace_application:
    application_df.APPLICATION_TYPE = application_df.APPLICATION_TYPE.replace(app,"Other")
    
# Check to make sure binning was successful
application_df.APPLICATION_TYPE.value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [22]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df.CLASSIFICATION.value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C2561        1
C1370        1
C1728        1
C6100        1
C1283        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [23]:
# Determine which values to replace if counts are less than 1000
replace_class = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in replace_class:
    application_df.CLASSIFICATION = application_df.CLASSIFICATION.replace(cls,"Other")
    
# Check to make sure binning was successful
application_df.CLASSIFICATION.value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [24]:
# Generate our categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()

In [27]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(application_df[application_cat]))
# encode_df = pd.get_dummies((application_df[application_cat])) # Alternative? Deshan

# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names(application_cat)
encode_df.head()

   APPLICATION_TYPE_Other  APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  \
0                       0                     1                     0
1                       0                     0                     0
2                       0                     0                     0
3                       0                     0                     0
4                       0                     0                     0

   APPLICATION_TYPE_T3  APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  \
0                    0                    0                    0
1                    1                    0                    0
2                    0                    0                    1
3                    1                    0                    0
4                    1                    0                    0

   APPLICATION_TYPE_T6  APPLICATION_TYPE_T7  APPLICATION_TYPE_T8  \
0                    0                    0                    0
1                    0                    0                    0
2                    0                    0                    0
3                    0                    0                    0
4                    0                    0                    0

   AFFILIATION_CompanySponsored  ...  INCOME_AMT_1-9999  \
0                             0  ...                  0
1                             0  ...                  1
2                             1  ...                  0
3                             1  ...                  0
4                             0  ...                  0

   INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  INCOME_AMT_10M-50M  \
0                       0                         0                   0
1                       0                         0                   0
2                       0                         0                   0
3                       1                         0                   0
4                       0                         1                   0

   INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  INCOME_AMT_50M+  \
0                 0                       0                0
1                 0                       0                0
2                 0                       0                0
3                 0                       0                0
4                 0                       0                0

   INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  SPECIAL_CONSIDERATIONS_Y
0                  0                         1                         0
1                  0                         1                         0
2                  0                         1                         0
3                  0                         1                         0
4                  0                         1                         0

[5 rows x 41 columns]

,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,1,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [28]:
# Merge one-hot encoded features and drop the originals
application_df = application_df.merge(encode_df,left_index=True, right_index=True)
application_df = application_df.drop(application_cat,1)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [29]:
application_df.columns

Index(['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL', 'APPLICATION_TYPE_Other',
       'APPLICATION_TYPE_T10', 'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3',
       'APPLICATION_TYPE_T4', 'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6',
       'APPLICATION_TYPE_T7', 'APPLICATION_TYPE_T8',
       'AFFILIATION_CompanySponsored', 'AFFILIATION_Family/Parent',
       'AFFILIATION_Independent', 'AFFILIATION_National', 'AFFILIATION_Other',
       'AFFILIATION_Regional', 'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200',
       'CLASSIFICATION_C2000', 'CLASSIFICATION_C2100', 'CLASSIFICATION_C3000',
       'CLASSIFICATION_Other', 'USE_CASE_CommunityServ', 'USE_CASE_Heathcare',
       'USE_CASE_Other', 'USE_CASE_Preservation', 'USE_CASE_ProductDev',
       'ORGANIZATION_Association', 'ORGANIZATION_Co-operative',
       'ORGANIZATION_Corporation', 'ORGANIZATION_Trust', 'INCOME_AMT_0',
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
       'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M',
       'SPECIAL_CONSIDERATIONS_N', 'SPECIAL_CONSIDERATIONS_Y'],
      dtype='object')

In [30]:
application_cat

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [31]:
# Split our preprocessed data into our features and target arrays
y = application_df["IS_SUCCESSFUL"].values
X = application_df.drop(["IS_SUCCESSFUL"],1).values
# y = application_df["IS_SUCCESSFUL"]
# X = application_df.drop(["IS_SUCCESSFUL"],1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [32]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [33]:
# Define the model - deep neural net
number_input_features = len(X_train[0])
# number_input_features = len(X_train.iloc[0])
hidden_nodes_layer1 =  80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 80)                3520
_________________________________________________________________
dense_1 (Dense)              (None, 30)                2430
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 31
=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [34]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [35]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Train on 25724 samples
Epoch 1/100
25724/25724 [==============================] - 7s 272us/sample - loss: 0.5692 - accuracy: 0.7234
Epoch 2/100
25724/25724 [==============================] - 3s 108us/sample - loss: 0.5558 - accuracy: 0.7310
Epoch 3/100
25724/25724 [==============================] - 3s 101us/sample - loss: 0.5530 - accuracy: 0.7317
Epoch 4/100
25724/25724 [==============================] - 3s 102us/sample - loss: 0.5511 - accuracy: 0.7315
Epoch 5/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5502 - accuracy: 0.7326
Epoch 6/100
25724/25724 [==============================] - 3s 114us/sample - loss: 0.5491 - accuracy: 0.7326
Epoch 7/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5483 - accuracy: 0.7337
Epoch 8/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5474 - accuracy: 0.7338
Epoch 9/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5471 - accuracy: 0.7350
Epoch 10/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5458 - accuracy: 0.7339
Epoch 11/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5460 - accuracy: 0.7357
Epoch 12/100
25724/25724 [==============================] - 3s 115us/sample - loss: 0.5453 - accuracy: 0.7356
Epoch 13/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5454 - accuracy: 0.7353
Epoch 14/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5452 - accuracy: 0.7348
Epoch 15/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5448 - accuracy: 0.7353
Epoch 16/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5438 - accuracy: 0.7363
Epoch 17/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5443 - accuracy: 0.7362
Epoch 18/100
25724/25724 [==============================] - 3s 116us/sample - loss: 0.5436 - accuracy: 0.7350
Epoch 19/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5434 - accuracy: 0.7369
Epoch 20/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5434 - accuracy: 0.7359
Epoch 21/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5430 - accuracy: 0.7374
Epoch 22/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5430 - accuracy: 0.7371
Epoch 23/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5422 - accuracy: 0.7369
Epoch 24/100
25724/25724 [==============================] - 3s 120us/sample - loss: 0.5423 - accuracy: 0.7372
Epoch 25/100
25724/25724 [==============================] - 3s 109us/sample - loss: 0.5420 - accuracy: 0.7381
Epoch 26/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5417 - accuracy: 0.7376
Epoch 27/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5415 - accuracy: 0.7376
Epoch 28/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5414 - accuracy: 0.7376
Epoch 29/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.5408 - accuracy: 0.7376
Epoch 30/100
25724/25724 [==============================] - 3s 113us/sample - loss: 0.5412 - accuracy: 0.7384
Epoch 31/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5407 - accuracy: 0.7390
Epoch 32/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5412 - accuracy: 0.7390
Epoch 33/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5409 - accuracy: 0.7374
Epoch 34/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5408 - accuracy: 0.7380
Epoch 35/100
25724/25724 [==============================] - 3s 109us/sample - loss: 0.5407 - accuracy: 0.7392
Epoch 36/100
25724/25724 [==============================] - 3s 116us/sample - loss: 0.5404 - accuracy: 0.7385
Epoch 37/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5406 - accuracy: 0.7390
Epoch 38/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5398 - accuracy: 0.7389
Epoch 39/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.5405 - accuracy: 0.7383
Epoch 40/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5400 - accuracy: 0.7394
Epoch 41/100
25724/25724 [==============================] - 3s 113us/sample - loss: 0.5397 - accuracy: 0.7395
Epoch 42/100
25724/25724 [==============================] - 3s 108us/sample - loss: 0.5400 - accuracy: 0.7385
Epoch 43/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5395 - accuracy: 0.7393
Epoch 44/100
25724/25724 [==============================] - 3s 109us/sample - loss: 0.5393 - accuracy: 0.7390
Epoch 45/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5394 - accuracy: 0.7383
Epoch 46/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5393 - accuracy: 0.7393
Epoch 47/100
25724/25724 [==============================] - 3s 118us/sample - loss: 0.5391 - accuracy: 0.7393
Epoch 48/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.5389 - accuracy: 0.7389
Epoch 49/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.5391 - accuracy: 0.7400
Epoch 50/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5389 - accuracy: 0.7393
Epoch 51/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.5386 - accuracy: 0.7391
Epoch 52/100
25724/25724 [==============================] - 3s 116us/sample - loss: 0.5389 - accuracy: 0.7396
Epoch 53/100
25724/25724 [==============================] - 3s 125us/sample - loss: 0.5385 - accuracy: 0.7397
Epoch 54/100
25724/25724 [==============================] - 3s 117us/sample - loss: 0.5386 - accuracy: 0.7397
Epoch 55/100
25724/25724 [==============================] - 3s 115us/sample - loss: 0.5381 - accuracy: 0.7403
Epoch 56/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5384 - accuracy: 0.7402
Epoch 57/100
25724/25724 [==============================] - 3s 108us/sample - loss: 0.5379 - accuracy: 0.7397
Epoch 58/100
25724/25724 [==============================] - 3s 120us/sample - loss: 0.5383 - accuracy: 0.7399
Epoch 59/100
25724/25724 [==============================] - 3s 108us/sample - loss: 0.5379 - accuracy: 0.7395
Epoch 60/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5380 - accuracy: 0.7406
Epoch 61/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5379 - accuracy: 0.7402
Epoch 62/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5381 - accuracy: 0.7395
Epoch 63/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5381 - accuracy: 0.7399
Epoch 64/100
25724/25724 [==============================] - 3s 121us/sample - loss: 0.5377 - accuracy: 0.7403
Epoch 65/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.5376 - accuracy: 0.7398
Epoch 66/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5375 - accuracy: 0.7406
Epoch 67/100
25724/25724 [==============================] - 3s 108us/sample - loss: 0.5379 - accuracy: 0.7405
Epoch 68/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.5373 - accuracy: 0.7406
Epoch 69/100
25724/25724 [==============================] - 3s 111us/sample - loss: 0.5378 - accuracy: 0.7402
Epoch 70/100
25724/25724 [==============================] - 3s 120us/sample - loss: 0.5373 - accuracy: 0.7409
Epoch 71/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5371 - accuracy: 0.7403
Epoch 72/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5373 - accuracy: 0.7404
Epoch 73/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5370 - accuracy: 0.7410
Epoch 74/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5369 - accuracy: 0.7405
Epoch 75/100
25724/25724 [==============================] - 3s 109us/sample - loss: 0.5368 - accuracy: 0.7411
Epoch 76/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5370 - accuracy: 0.7410
Epoch 77/100
25724/25724 [==============================] - 3s 100us/sample - loss: 0.5372 - accuracy: 0.7401
Epoch 78/100
25724/25724 [==============================] - 3s 101us/sample - loss: 0.5367 - accuracy: 0.7405
Epoch 79/100
25724/25724 [==============================] - 3s 101us/sample - loss: 0.5367 - accuracy: 0.7407
Epoch 80/100
25724/25724 [==============================] - 3s 100us/sample - loss: 0.5367 - accuracy: 0.7407
Epoch 81/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5371 - accuracy: 0.7402
Epoch 82/100
25724/25724 [==============================] - 3s 106us/sample - loss: 0.5367 - accuracy: 0.7402
Epoch 83/100
25724/25724 [==============================] - 3s 100us/sample - loss: 0.5365 - accuracy: 0.7407
Epoch 84/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5364 - accuracy: 0.7410
Epoch 85/100
25724/25724 [==============================] - 3s 102us/sample - loss: 0.5365 - accuracy: 0.7409
Epoch 86/100
25724/25724 [==============================] - 3s 103us/sample - loss: 0.5365 - accuracy: 0.7410
Epoch 87/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5362 - accuracy: 0.7412
Epoch 88/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5368 - accuracy: 0.7403
Epoch 89/100
25724/25724 [==============================] - 3s 102us/sample - loss: 0.5364 - accuracy: 0.7403
Epoch 90/100
25724/25724 [==============================] - 3s 100us/sample - loss: 0.5364 - accuracy: 0.7406
Epoch 91/100
25724/25724 [==============================] - 3s 100us/sample - loss: 0.5357 - accuracy: 0.7412
Epoch 92/100
25724/25724 [==============================] - 3s 101us/sample - loss: 0.5363 - accuracy: 0.7409
Epoch 93/100
25724/25724 [==============================] - 3s 110us/sample - loss: 0.5359 - accuracy: 0.7414
Epoch 94/100
25724/25724 [==============================] - 3s 110us/sample - loss: 0.5364 - accuracy: 0.7408
Epoch 95/100
25724/25724 [==============================] - 3s 101us/sample - loss: 0.5363 - accuracy: 0.7409
Epoch 96/100
25724/25724 [==============================] - 3s 100us/sample - loss: 0.5360 - accuracy: 0.7417
Epoch 97/100
25724/25724 [==============================] - 3s 105us/sample - loss: 0.5357 - accuracy: 0.7407
Epoch 98/100
25724/25724 [==============================] - 3s 107us/sample - loss: 0.5358 - accuracy: 0.7413
Epoch 99/100
25724/25724 [==============================] - 3s 114us/sample - loss: 0.5360 - accuracy: 0.7406
Epoch 100/100
25724/25724 [==============================] - 3s 109us/sample - loss: 0.5355 - accuracy: 0.7408

In [36]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 1s - loss: 0.5558 - accuracy: 0.7250
Loss: 0.5558205437104139, Accuracy: 0.7250145673751831

# Random Forest

In [43]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Create a random forest classifer
rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

# Fitting the model
rf_model.fit(X_train_scaled, y_train)

# Evaluating the model
y_pred = rf_model.predict(X_test_scaled)
print(f" Random Forest predictive accuracy: {accuracy_score(y_test, y_pred):.3f}")

 Random Forest predictive accuracy: 0.710